accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:article_pk>/like_root/', views.like_root, name='like_root'),
    path('<int:article_pk>/like_profile/', views.like_profile, name='like_profile'),
    path('<str:tag_name>/', views.tag_search, name='tag_search'),
]

crud/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views as accounts_views
from articles import views as articles_views


urlpatterns = [
    path('', articles_views.index, name='root'),
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('<str:username>/', accounts_views.profile, name='profile'),
    # 순서가 매우 중요..! 앞에서부터 찾아보고 마지막에 걸리게
    # 그리고 admin, articles, accouunts 는 가입할 수 없게 만들어야 함
    path('<str:username>/follow/', accounts_views.follow, name='follow'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings

class User(AbstractUser):
    followers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="followings")

articles/models.py
from django.db import models
from django.conf import settings
from taggit.managers import TaggableManager

class Article(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles')
    tags = TaggableManager()

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()

articles/forms.py
from django import forms
from .models import Article


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        exclude = ['created_at', 'updated_at', 'user', 'like_users']

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import AuthenticationForm
from .forms import CustomUserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login as auth_login, logout as auth_logout
from django.contrib.auth import get_user_model

User = get_user_model()


def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('articles:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)

def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('articles:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)

@login_required
def logout(request):
    auth_logout(request)
    return redirect('articles:index')

@login_required
def follow(request, username):
    person = get_object_or_404(User, username=username)
    user = request.user
    if user != person:
        if user in person.followers.all():
            person.followers.remove(user)
        else:
            person.followers.add(user)
    # else:
    #     message.info('스스로는 팔로우 하실 수 없습니다.')
    return redirect('profile', person.username)


@login_required
def profile(request, username):
    person = get_object_or_404(User, username=username)
    context = {
        'person': person,
    }
    return render(request, 'accounts/profile.html', context)

articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Article
from .forms import ArticleForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
import random

User = get_user_model()


@login_required
def index(request):
    users = User.objects.all() # 전체 유저 그룹
    followings = request.user.followings.all() # 사용자가 팔로잉하고 있는 유저 그룹
    unfollowings = users.difference(followings) # 사용자가 팔로잉하고 있지 않은 유저 그룹
    if len(unfollowings) >= 5: # 만약 그 수가 5 이상이라면
        # 랜덤하게 5명만 뽑아 추천.
        # queryset은 random.shufle()이 먹히지 않는다. 따라서 아래와 같이 구현해야한다.
        # unfollowings = sorted(unfollowings, key=lambda x: random.random())[:5]
        # 서로 많은 친구(내가 팔로잉하고 있는 유저)를 공유하고 있는 사람 5명 뽑아 추천
        unfollowings = sorted(unfollowings, reverse=True, key=lambda x: x.followings.all().intersection(request.user.followings.all()).count())[:5]

    articles = [] # 넘겨줄 글 목록
    for following in followings: # 팔로잉 하고 있는 유저
        for article in following.article_set.all(): # 해당 유저가 쓴 글
            articles.append(article)
    # 해당 글들 생성시간 순으로 정렬
    articles = sorted(articles, key=lambda article: article.created_at)

    context = {
        'unfollowings': unfollowings,
        'articles': articles,
    }
    return render(request, 'articles/index.html', context)

@login_required
def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        if form.is_valid():
            article = form.save(commit=False)
            article.user = request.user
            article.save()
            form.save_m2m()
            return redirect('profile', request.user.username)
    else:
        form = ArticleForm()
    context = {
        'form': form,
    }
    return render(request, 'articles/form.html', context)

@login_required
def like_root(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    user = request.user
    if request.user in article.like_users.all():
        article.like_users.remove(user)
    else:
        article.like_users.add(user)
    return redirect('root')

@login_required
def like_profile(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    user = request.user
    if request.user in article.like_users.all():
        article.like_users.remove(user)
    else:
        article.like_users.add(user)
    return redirect('profile', article.user.username)

@login_required
def tag_search(request, tag_name):
    tag_articles = Article.objects.filter(tags__name__in=[tag_name]).distinct()

    context = {
        'tag_articles':tag_articles,
        'tag_name':tag_name,
    }
    return render(request, 'articles/tag_articles.html', context)

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
<h1 class="text-center">Login</h1>
<hr>
<form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button "Login" button_type="submit" button_class="btn-primary" %}
</form>
<hr>
<p class="text-center">계정이 없으신가요? <a href="{% url 'accounts:signup' %}">가입하기</a></p>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1 class="text-center">{{ person.username }}님의 프로필</h1>
    <hr>
    <div class="d-flex justify-content-between">
        <div>
            {% if request.user != person %}
            {% if request.user in person.followers.all %}
                <h5 class="bg-primary rounded p-2"><a class="text-white" href="{% url 'follow' person.username %}">Unfollow</a></h5>
            {% else %}
                <h5 class="bg-primary rounded p-2"><a class="text-white" href="{% url 'follow' person.username %}">Follow</a></h5>
            {% endif %}
            {% endif %}
        </div>
        <div class="d-flex justify-content-end">
            <div class="dropdown mx-2">
              <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                팔로워: {{ person.followers.count }}
              </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                {% for follower in person.followers.all %}
                    <a class="dropdown-item" href="{% url 'profile' follower.username %}">{{ follower.username }}</a>
                {% endfor %}
              </div>
            </div>
            <div class="dropdown mx-2">
              <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                팔로잉: {{ person.followings.count }}
              </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                {% for following in person.followings.all %}
                    <a class="dropdown-item" href="{% url 'profile' following.username %}">{{ following.username }}</a>
                {% endfor %}
              </div>
            </div>
        </div>
    </div>
    <hr>
    <div class="row">
        {% for article in person.article_set.all %}
        <div class="card col-4" style="width: 18rem;">
          <div class="card-body">
            <h5 class="card-title">{{ article.title }}</h5>
            <!--<p class="card-text"><a href="{% url 'profile' article.user.username %}">{{ article.user.username }}</a></p>-->
            <p class="card-text">{{ article.content }}</p>
            {% for tag in article.tags.all %}
            <a href="{% url 'articles:tag_search' tag.name %}" class="card-text d-inline">#{{ tag }} </a>
            {% endfor %}
            <p class="card-text">{{ article.created_at }}</p>
            {% if user in article.like_users.all %}
            <a href="{% url 'articles:like_profile' article.id %}" style="font-size: 2em; color: red;"><i class="far fa-kiss-wink-heart"></i></a>
            {% else %}
            <a href="{% url 'articles:like_profile' article.id %}" style="font-size: 2em; color: Dodgerblue;"><i class="far fa-kiss"></i></a>
            {% endif %}
            Like: {{ article.like_users.count }}
          </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
<h1 class="text-center">Signup</h1>
<hr>
<form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button "Signup" button_type="submit" button_class="btn-primary" %}
</form>
{% endblock %}

articles/templates/articles/form.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
<h1 class="text-center">New Article</h1>
<hr>
<form action="" method = "POST">
{% csrf_token %}
{% bootstrap_form form %}
{% bootstrap_button "Save" button_type="submit" button_class="btn-primary" %}
</form>
{% endblock %}

articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12 d-flex flex-column align-items-center">
          <h1 class="text-center">새로운 사람들을 팔로우 해보세요!</h1>
          <ul>
          {% for user in unfollowings %}
            {% if user != request.user %}
              <li class="m-3 d-inline"><a href="{% url 'profile' user.username %}">{{ user.username }}</a></li>
            {% endif %}
          {% endfor %}
          </ul>
        </div>
        <hr>
        {% for article in articles %}
        <div class="card col-4" style="width: 18rem;">
          <div class="card-body">
            <h5 class="card-title">{{ article.title }}</h5>
            <p class="card-text"><a href="{% url 'profile' article.user.username %}">{{ article.user.username }}</a></p>
            <p class="card-text">{{ article.content }}</p>
            {% for tag in article.tags.all %}
            <a href="{% url 'articles:tag_search' tag.name %}" class="card-text d-inline">#{{ tag }} </a>
            {% endfor %}
            <p class="card-text">{{ article.created_at }}</p>
            {% if user in article.like_users.all %}
            <a href="{% url 'articles:like_root' article.id %}" style="font-size: 2em; color: red;"><i class="far fa-kiss-wink-heart"></i></a>
            {% else %}
            <a href="{% url 'articles:like_root' article.id %}" style="font-size: 2em; color: Dodgerblue;"><i class="far fa-kiss"></i></a>
            {% endif %}
            Like: {{ article.like_users.count }}
          </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

articles/templates/articles/like.html
{% if user in article.like_users.all %}
<a href="{% url 'articles:like' article.id %}" style="font-size: 2em; color: red;"><i class="far fa-kiss-wink-heart"></i></a>
{% else %}
<a href="{% url 'articles:like' article.id %}" style="font-size: 2em; color: Dodgerblue;"><i class="far fa-kiss"></i></a>
{% endif %}
Like: {{ article.like_users.count }}

articles/templates/articles/tag_articles.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12 d-flex flex-column align-items-center">
          <h1 class="text-center">#{{ tag_name }}</h1>
        </div>
        <hr>
        {% for article in tag_articles %}
        <div class="card col-4" style="width: 18rem;">
          <div class="card-body">
            <h5 class="card-title">{{ article.title }}</h5>
            <p class="card-text"><a href="{% url 'profile' article.user.username %}">{{ article.user.username }}</a></p>
            <p class="card-text">{{ article.content }}</p>
            {% for tag in article.tags.all %}
            <a href="{% url 'articles:tag_search' tag.name %}" class="card-text d-inline">#{{ tag }} </a>
            {% endfor %}
            <p class="card-text">{{ article.created_at }}</p>
            {% if user in article.like_users.all %}
            <a href="{% url 'articles:like_root' article.id %}" style="font-size: 2em; color: red;"><i class="far fa-kiss-wink-heart"></i></a>
            {% else %}
            <a href="{% url 'articles:like_root' article.id %}" style="font-size: 2em; color: Dodgerblue;"><i class="far fa-kiss"></i></a>
            {% endif %}
            Like: {{ article.like_users.count }}
          </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load bootstrap4 %}
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://kit.fontawesome.com/e26b215976.js" crossorigin="anonymous"></script>
    <title>#instacram</title>
    {% bootstrap_css %}
</head>
<body>
    <nav class="sticky-top navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'root' %}">#instacram</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
              <a class="nav-item nav-link disable"><p class="mb-0">{{ user.username }}님 환영합니다.</p></a>
              <a class="nav-item nav-link" href="{% url 'accounts:logout' %}">Logout</a>
              <a class="nav-item nav-link" href="{% url 'profile' request.user.username %}">My Page</a>
            {% else %}
              <a class="nav-item nav-link" href="{% url 'accounts:login' %}">Login</a>
              <a class="nav-item nav-link" href="{% url 'accounts:signup' %}">Signup</a>
            {% endif %}
              <a class="nav-item nav-link" href="{% url 'articles:create' %}">New Article</a>
        </div>
      </div>
    </nav>
    <div class="container mt-3" style="margin-bottom:60px">
    {% if messages %}
    {% for message in messages %}
        <div class="row" style="margin:20px auto;">
        <div class="col-sm-12">
            <div class="alert alert-info">
            <strong class="text-center">{{ message.message }}</strong>
            </div>
        </div>
        </div>
    {% endfor %}
    {% endif %}
    {% block content %}
    {% endblock %}
    </div>
    <!-- Footer -->
    <footer class="fixed-bottom page-footer font-small bg-dark" style="height:40px">
      <h3 class="text-white text-center">#instacram, by SunHwan Park</h3>
    </footer>
    <!-- Footer -->
    {% bootstrap_javascript jquery='full' %}
</body>
</html>